server:
      port: 8091
spring:
  cloud:
    config:
       server:
           git:
             default-label: eureka
             uri : https://github.com/dinopantonelli/Microservices_SpringBoot_SpringCloud
             search-paths: config-data
  application:
    name: config-service             
  jpa:
    show-sql: false 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pruebamicroservicio1
    username: root
    password: 